from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

# Create your views here.
from tensorflow import keras
from keras.models import load_model
from keras.preprocessing import image
from tensorflow import Graph 
import tensorflow as tf
import numpy as np
from .models import Uploads
from django.contrib.auth.models import User

img_height,img_width = 224,224
labelInfo = ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']
disInfo= {'Apple___Apple_scab': ['Apple-Apple Scab','Apple Scab is a fungal disease which can affect the leaves, fruit, and twigs of flowering, ornamental trees such as crabapple, hawthorn (Venturia inequalis) and pear (V. pirina). Infection on newly emerging leaves is favored by wet and cool spring conditions. Early symptoms of Apple Scab are brownish-green spots on the leaves or fruit. As the infection progresses, the spots become darker and more prominent and take on a velvety texture due to spore (conidia) formation. Severe infections result in leaf drop off and thinned canopy early, in the summer months.','Apple Scab can be treated with: Propizol® Fungicide (Crabapples only) or PHOSPHO-jet. *Propizol is for ornamental use only. Fruit are not to be used for human or animal consumption.'], 
      'Apple___Black_rot': ['Apple-Black Rot','Black rot is occasionally a problem on Minnesota apple trees.This fungal disease causes leaf spot, fruit rot and cankers on branches.Trees are more likely to be infected if they are: 1.Not fully hardy in Minnesota. 2.Infected with fire blight. 3.Stressed by environmental factors like drought. Manage black rot by practicing good sanitation, taking good care of your trees and pruning your trees correctly. Fungicides are rarely needed to manage black rot.','Consider using fungicides only after you’ve used good cultural practices and the disease hasn’t gone away. Captan and sulfur products are labeled for control of both scab and black rot. A scab spray program including these chemicals may help prevent the frog-eye leaf spot of black rot, as well as the infection of fruit. These sprays will not control or prevent infection of branches.'], 
      'Apple___Cedar_apple_rust': ['Apple-Cedar Apple Rust','Instead of galls, infected apple and crabapple trees manifest circular yellow spots on the upper surface of their leaves soon after bloom. Later in the summer, brownish cylindrical tubes with hairs sticking out appear underneath the yellow spots, or on the twigs and fruit. These tubes produce the aeciospores that will complete the cycle by infecting the needles of junipers. At the least, the infected fruit may be of marginal quality. Worst case scenario – they drop off the tree.','Since the juniper galls are the source of the spores that infect the apple trees, cutting them is a sound strategy if there aren’t too many of them. The best way to do this is to prune the branches about 4-6 inches below the galls. If your tree has a history of infection with cedar apple rust, you will want to get ahead of the infection and take preemptive measures. Make sure you choose a formulation that is labeled for use on fruit trees such as the one shown above, since several types available today are not designed for this purpose. Typically, you should spray every 7-10 days during the period of infection. After that, you no longer need to treat your tree for the rest of the year.'], 
      'Apple___healthy': ['Healthy Apple Leaf','It is healthy.','No treatment required.'], 
      'Blueberry___healthy': ['Healthy Blueberry Leaf','It is healthy.','No treatment required.'], 
      'Cherry_(including_sour)___Powdery_mildew': ['Cherry-Powdery Mildew','Initial symptoms, often occurring 7 to 10 days after the onset of the first irrigation, are light roughly-circular, powdery looking patches on young, susceptible leaves (newly unfolded, and light green expanding leaves). Older leaves develop an age-related (ontogenic) resistance to powdery mildew and are naturally more resistant to infection than younger leaves. Look for early leaf infections on root suckers, the interior of the canopy or the crotch of the tree where humidity is high. In contrast to other fungi, powdery mildews do not need free water to germinate but germination and fungal growth are favored by high humidity (Grove & Boal, 1991a). The disease is more likely to initiate on the undersides (abaxial) of leaves.','The key to managing powdery mildew on the fruit is to keep the disease off of the leaves. Most synthetic fungicides are preventative, not eradicative, so be pro-active about disease prevention. Maintain a consistent program from shuck fall through harvest. Consider post-harvest preventative measures (e.g. application of sulfur, prevent trees from pushing for leaf growth) to obstruct the fungus from overwintering. Preharvest fungicide applications should be based on the residual period of the product. Rotate between modes of action (MOA) in order to avoid resistance. Also, visit the Fungicide Resistance Action Committee web page for updated fungicide information (http://www.frac.info/).'], 
      'Cherry_(including_sour)___healthy': ['Healthy Cherry Leaf','It is healthy.','No treatment required.'], 
      'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': ['Corn-Cercospora Leaf spot/Gray Leaf spot','Gray leaf spot (GLS) is a common fungal disease in the United States caused by the pathogen Cercospora zeae-maydis in corn. Disease development is favored by warm temperatures, 80°F or 27 °C; and high humidity, relative humidity of 90% or higher for 12 hours or more. Cercospora zeae-maydis overwinters in corn residue, allowing inoculum to build up from year to year in fields. Cropping systems with reduced- or no-till and/or continuous corn are at higher risk for gray leaf spot outbreaks. Conducive weather conditions encourage the rapid spread of disease near the end of summer and early fall, when corn plants allocate more resources to grainfill.','Cercospora zeae-maydis overwinters in corn debris, so production practices such as tillage and crop rotation that reduce the amount corn residue on the surface will decrease the amount of primary inoculum. Crop rotation away from corn can reduce disease pressure, but multiple years may be necessary in no-till scenarios. During the growing season, foliar fungicides can be used to manage gray leaf spot outbreaks. Farmers must consider the cost of the application and market value of their corn before determining if fungicides will be an economical solution to GLS.'], 
      'Corn_(maize)___Common_rust_': ['Corn-Common Rust','Common rust of sweet corn is caused by the fungus Puccinia sorghi and can result in serious losses in yield or quality of sweet corn. Sweet corn rust occurs in temperate to sub-tropical regions and overwinters in the southern Unites States and Mexico. Summer storms and winds blow the spores of corn rust fungus into the Corn Belt.Read more at Gardening Know How: Sweet Corn Rust Treatment – Learn About Corn Rust Fungus Control.','To reduce the incidence of corn rust, plant only corn that has resistance to the fungus. Resistance is either in the form of race-specific resistance or partial rust resistance. In either case, no sweet corn is completely resistant. If the corn begins to show symptoms of infection, immediately spray with a fungicide. The fungicide is most effective when started at the first sign of infection. Two applications may be necessary. Contact your local extension office for advice regarding specific fungicides and their uses. Read more at Gardening Know How: Sweet Corn Rust Treatment – Learn About Corn Rust Fungus Control:https://www.gardeningknowhow.com/edible/vegetables/corn/corn-rust-fungus-control.htm'], 
      'Corn_(maize)___Northern_Leaf_Blight': ['Corn-Northern Leaf Blight','Northern corn leaf blight (NCLB) is caused by the fungus Setosphaeria turcica. Symptoms usually appear first on the lower leaves. Leaf lesions are long (1 to 6 inches) and elliptical, gray-green at first but then turn pale gray or tan. Under moist conditions, dark gray spores are produced, usually on the lower leaf surface, which give lesions a "dirty" gray appearance. Entire leaves on severely blighted plants can die, so individual lesions are not visible. Lesions may occur on the outer husk of ears, but the kernels are not infected. On hybrids that contain an Ht gene for resistance to the fungus, lesions are smaller, chlorotic, and may develop into linear streaks. These lesions rarely produce spores.','Resistant hybrids are available and should be grown when disease is a potential problem. There are two types of resistance to NCLB, monogenic (Ht genes - resistance that is controlled by one gene) and polygenic (resistance that is controlled by many genes). Hybrids with an Ht gene are susceptible to some races of the pathogen. Polygenic resistance provides resistance to all races, but the resistance is not as absolute as Ht resistance. Crop rotation and surface residue reduction through tillage can decrease inoculum. There are several foliar fungicides that are labeled for NCLB.'], 
      'Corn_(maize)___healthy': ['Healthy Corn(Maize) Leaf','It is healthy.','No treatment required.'], 
      'Grape___Black_rot': ['Grape-Black Rot','Black rot is one of the most damaging grape diseases in Ohio. All cultivated varieties of grapes are susceptible to infection by the black rot fungus. If not controlled, some or all of the grapes within a cluster will be rotted. The disease is favored by warm, humid weather as is found during the summer throughout most of Ohio. Before good control measures were devised, vineyards along the Ohio River often were hard hit. Grape growers commonly lost most of their crop, and the grape industry was literally driven out of the area','Mancozeb, and Ziram are all highly effective against black rot. Because these fungicides are strictly protectants, they must be applied before the fungus infects or enters the plant. They protect fruit and foliage by preventing spore germination. They will not arrest lesion development after infection has occurred. Mancozeb provides an excellent foundation for a protectant spray program for grapes in Ohio. It is a good protectant fungicide that will provide good to excellent control of downy mildew and Phomopsis cane and leaf spot in addition to black rot. The major problem with Mancozeb is a 66-day pre harvest interval (PHI) on grapes. It cannot be applied within 66 days of harvest. Mancozeb is available under many trade names and formulations. Mancozeb would be my protectant fungicide of choice for controlling black rot in the backyard.'], 
      'Grape___Esca_(Black_Measles)': ['Grape-Black Measles(Esca)','Esca, Botryosphaeria dieback, Eutypa dieback, and Phomopsis dieback make up a complex of "trunk diseases" caused by different wood-infecting fungi. The foliar symptom of Esca is an interveinal "striping". The "stripes", which start out as dark red in red cultivars and yellow in white cultivars, dry and become necrotic. Foliar symptoms may occur at any time during the growing season, but are most prevalent during July and August. They are often restricted to an individual shoot or to shoots originating from the same spur or cane. Symptomatic leaves can dry completely and drop prematurely. On berries, small, round, dark spots each bordered by a brown-purple ring, may occur. These fruit spots, which are better viewed on white cultivars, may appear at any time between fruit set and ripening. In severely affected vines, the berries often crack and dry or are subject to spoilage. Symptomatic fruit is found only on shoots with symptomatic leaves, but you can find shoots with symptomatic leaves and no symptomatic fruit.','Delayed pruning takes advantage of reduced susceptibility of pruning wounds to infection and avoids the period of highest spore release during typically frequent rain events in December and January. Double pruning is a modified version of delayed pruning for large acreages of cordon-trained, spur-pruned vines; pre-pruning is done in early winter (most often mechanically) by cutting canes to 12 to 18-inches above the final pruning cuts, followed by hand pruning to create spurs in February or later. If delayed pruning is not feasible or for additional protection, consider treating pruning wounds with a protectant. Keep in mind that all wounds made in the dormant season are susceptible; this includes pruning cuts made to canes or larger cuts made to re-position/re-orient spurs. Although preventative practices are most effective in young vineyards (before the vines become infected by trunk diseases), these practices have some utility in diseased mature vineyards. Wood cankers are very localized, thus protecting more pruning wounds means fewer new cankers each year resulting in fewer dead spurs, arms or canes over time. Post-infection practices (sanitation and vine surgery) for use in diseased, mature vineyards are not as effective and are far more costly than adopting preventative practices (delayed pruning, double pruning, and applications of pruning-wound protectants) in young vineyards.'], 
      'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': ['Grape-Isariopsis Leaf spot','On leaf surface we will see lesions which are irregularly shaped (2 to 25 mm in diameter). Initially lesions are dull red to brown in color turn black later. If disease is severe this lesions may coalesce. On berries we can see symptom similar to black rot but the entire clusters will collapse. Caused by Fungus. Common in tropical and subtropical grapes. The disease appear late in the season. Cynthiana and Cabernet Sauvignon are susceptible to this pathogen.','Fungicides sprayed for other diseases in the season may help to reduce this disease.'], 
      'Grape___healthy': ['Healthy Grape Leaf','It is healthy.','No treatment required.'], 
      'Orange___Haunglongbing_(Citrus_greening)': ['Orange-Citrus Greening','Citrus greening or Huanglongbing is one of the most severe diseases of citrus. It has reduced yields in all types of citrus wherever it occurs in Asia, from China and the Philippines to the Arabian peninsula, and to Africa. It is one of the diseases the rest of the citrus-producing countries are guarding against and bracing for its eventual spread to them. Symptoms of citrus greening consist of smaller leaves, yellowing of the leaves of part or, usually, the entire canopy of the trees, reduced foliage, and severe dieback of twigs.','Control of citrus greening depends on exclusion of the pathogen from a citrus-producing area, use of disease-free propagating material, removal of infected trees as soon as they are detected, and attempts to control the insect vectors with insecticides or by biological control.'], 
      'Peach___Bacterial_spot': ['Peach-Bacterial Spot','Bacterial spot is an important disease of peaches, nectarines, apricots, and plums caused by Xanthomonas campestris pv. pruni. Symptoms of this disease include fruit spots, leaf spots, and twig cankers. Fruit symptoms include pitting, cracking, gumming, and watersoaked tissue, which can make the fruit more susceptible to brown rot, rhizopus, and other fungal infections. Severe leaf spot infections can cause early defoliation. Severe defoliation can result in reduced fruit size, and sunburn and cracking of fruit. Early defoliated trees are reduced in vigor and winter hardiness.','Compounds available for use on peach and nectarine for bacterial spot include copper, oxytetracycline (Mycoshield and generic equivalents), and syllit+captan; however, repeated applications are typically necessary for even minimal disease control. Oxytetracycline is generally considered the most effective compound and the least prone to phytotoxicity problems (damage to plant tissue), but also perhaps most likely to lose effectiveness with the appearance of bacterial strains with resistance. There is some evidence that the hydrochloride form of oxytetracycline (Fireline) is more effective than the calcium form Mycoshield.'], 
      'Peach___healthy': ['Healthy Peach Leaf','It is healthy.','No treatment required.'], 
      'Pepper,_bell___Bacterial_spot': ['Pepper-Bell Bcterial spot','Bacterial leaf spot, caused by Xanthomonas campestris pv. vesicatoria, is the most common and destructive disease for peppers in the eastern United States. It is a  gram-negative, rod-shaped bacterium that can survive in seeds and plant debris from one season to another (Frank et al. 2005). Different strains or races of the bacterium are cultivar-specific, causing disease symptoms in certain varieties due to stringent host specificity. Bacterial leaf spot can devastate a pepper crop by early defoliation of infected leaves and disfiguring fruit. In severe cases, plants may die as it is extremely difficult to find a cure once the disease takes hold. However, there are several options for growers to prevent it from occurring and spreading.','Any disease management strategy should be focused on breaking up the disease cycle. This can be achieved by using the following formula: DM=S2IR. This formula states that: \'disease management is achieved by stopping or reducing survival of the pathogen, spread of the pathogen, infection of plants and reproduction of the pathogen.\' For bacterial leaf spot, the following methods can be used to reduce the survival, spread and reproduction of bacteria and to minimize the infection of plants: using resistant varieties, seed treatment, foliage treatment and using an integrated strategy.'], 
      'Pepper,_bell___healthy': ['Heathy Pepper Leaf','It is healthy.','No treatment required.'], 
      'Potato___Early_blight': ['Potato-Early Blight','Early blight of potato is a common disease found in most potato growing regions. The disease is caused by the fungus Alternaria solani, which can also afflict tomatoes and other members of the potato family. Potatoes become infected with early blight when foliage has become excessively wet due to rain, fog, dew, or irrigation. Although not a terminal disease, severe infections can be fairly detrimental. In contrast to its name, early blight rarely develops early; it actually usually affects mature foliage rather than young, tender leaves.','The spores and mycelia of the pathogen survive in infested plant debris and soil, in infected tubers and in overwintering host crops and weeds. Spores are produced when temperatures are between 41-86 F. (5-30 C.) with alternating periods of wetness and dryness. These spores are then spread through wind, splashing rain, and irrigation water. They gain entry via wounds caused by mechanical injury or insect feeding. Lesions begin to appear 2-3 days after the initial infection. Treatment of early blight includes prevention by planting potato varieties that are resistant to the disease; late maturing are more resistant than early maturing varieties. Read more at Gardening Know How: Potato Early Blight Treatment – Managing Potatoes With Early Blight https://www.gardeningknowhow.com/edible/vegetables/potato/potato-early-blight-treatment.htm'], 
      'Potato___Late_blight': ['Potato Late Blight','Found on tomato and potato plants, late blight is caused by the fungus Phytophthora infestans and is common throughout the United States. True to its name, the disease occurs later in the growing season with symptoms often not appearing until after blossom. Late blight first appears on the lower, older leaves as water-soaked, gray-green spots. As the disease matures, these spots darken and a white fungal growth forms on the undersides. Eventually the entire plant will become infected. Crops can be severely damaged. Unlike other fungal diseases, this plant problem does not overwinter in the soil or on garden trash. Instead the spores are introduced by infected tubers, transplants or seeds. Wind will also carry the disease from nearby gardens. Warm temperatures (70-80˚F) and wet, humid conditions promote its rapid spread.','Plant resistant cultivars when available. Remove volunteers from the garden prior to planting and space plants far enough apart to allow for plenty of air circulation. Water in the early morning hours, or use soaker hoses, to give plants time to dry out during the day — avoid overhead irrigation. Destroy all tomato and potato debris after harvest (see Fall Garden Cleanup).'], 
      'Potato___healthy': ['Healthy Potato Leaf','It is healthy.','No treatment required.'], 
      'Raspberry___healthy': ['Healthy Raspberry Leaf','It is healthy.','No treatment required.'], 
      'Soybean___healthy': ['Healthy Soybean Leaf','It is healthy.','No treatment required.'], 
      'Squash___Powdery_mildew': ['Squash-Powdery Mildew','Initial symptoms, often occurring 7 to 10 days after the onset of the first irrigation, are light roughly-circular, powdery looking patches on young, susceptible leaves (newly unfolded, and light green expanding leaves). Older leaves develop an age-related (ontogenic) resistance to powdery mildew and are naturally more resistant to infection than younger leaves. Look for early leaf infections on root suckers, the interior of the canopy or the crotch of the tree where humidity is high. In contrast to other fungi, powdery mildews do not need free water to germinate but germination and fungal growth are favored by high humidity (Grove & Boal, 1991a). The disease is more likely to initiate on the undersides (abaxial) of leaves.','The key to managing powdery mildew on the fruit is to keep the disease off of the leaves. Most synthetic fungicides are preventative, not eradicative, so be pro-active about disease prevention. Maintain a consistent program from shuck fall through harvest. Consider post-harvest preventative measures (e.g. application of sulfur, prevent trees from pushing for leaf growth) to obstruct the fungus from overwintering. Preharvest fungicide applications should be based on the residual period of the product. Rotate between modes of action (MOA) in order to avoid resistance. Also, visit the Fungicide Resistance Action Committee web page for updated fungicide information (http://www.frac.info/).'], 
      'Strawberry___Leaf_scorch': ['Strawberry_-Leaf Scorch','Scorched strawberry leaves are caused by a fungal infection which affects the foliage of strawberry plantings. The fungus responsible is called Diplocarpon earliana. Strawberries with leaf scorch may first show signs of issue with the development of small purplish blemishes that occur on the topside of leaves. Over time, the spots will continue to grow larger and darken. In severe cases, dark spots may even cover entire portions of strawberry plant leaves and cause them to completely dry and fall from the plant. Though the foliage of the infected plants is not aesthetically pleasing, it is seldom that the presence of this fungus impacts the quality of the strawberry crop itself.','While leaf scorch on strawberry plants can be frustrating, there are some strategies which home gardeners may employ to help prevent its spread in the garden. The primary means of strawberry leaf scorch control should always be prevention. Since this fungal pathogen overwinters on the fallen leaves of infected plants, proper garden sanitation is key. This includes the removal of infected garden debris from the strawberry patch, as well as the frequent establishment of new strawberry transplants. The creation of new plantings and strawberry patches is key to maintaining a consistent strawberry harvest, as older plants are more likely to show signs of severe infection.'], 
      'Strawberry___healthy': ['Healthy Strawberry Leaf','It is healthy.','No treatment required.'], 
      'Tomato___Bacterial_spot': ['Tomato -Bacterial Spot','Bacterial spot of tomato is a potentially devastating disease that, in severe cases, can lead to unmarketable fruit and even plant death.  Bacterial spot can occur wherever tomatoes are grown, but is found most frequently in warm, wet climates, as well as in greenhouses.  The disease is often an issue in Wisconsin.','A plant with bacterial spot cannot be cured.  Remove symptomatic plants from the field or greenhouse to prevent the spread of bacteria to healthy plants.  Burn, bury or hot compost the affected plants and DO NOT eat symptomatic fruit.  Although bacterial spot pathogens are not human pathogens, the fruit blemishes that they cause can provide entry points for human pathogens that could cause illness.'], 
      'Tomato___Early_blight': ['Tomato-Early Blight','Early blight of potato is a common disease found in most potato growing regions. The disease is caused by the fungus Alternaria solani, which can also afflict tomatoes and other members of the potato family. Potatoes become infected with early blight when foliage has become excessively wet due to rain, fog, dew, or irrigation. Although not a terminal disease, severe infections can be fairly detrimental. In contrast to its name, early blight rarely develops early; it actually usually affects mature foliage rather than young, tender leaves.','The spores and mycelia of the pathogen survive in infested plant debris and soil, in infected tubers and in overwintering host crops and weeds. Spores are produced when temperatures are between 41-86 F. (5-30 C.) with alternating periods of wetness and dryness. These spores are then spread through wind, splashing rain, and irrigation water. They gain entry via wounds caused by mechanical injury or insect feeding. Lesions begin to appear 2-3 days after the initial infection. Treatment of early blight includes prevention by planting potato varieties that are resistant to the disease; late maturing are more resistant than early maturing varieties. Read more at Gardening Know How: Potato Early Blight Treatment – Managing Potatoes With Early Blight https://www.gardeningknowhow.com/edible/vegetables/potato/potato-early-blight-treatment.htm'], 
      'Tomato___Late_blight': ['Tomato Late Blight','Found on tomato and potato plants, late blight is caused by the fungus Phytophthora infestans and is common throughout the United States. True to its name, the disease occurs later in the growing season with symptoms often not appearing until after blossom. Late blight first appears on the lower, older leaves as water-soaked, gray-green spots. As the disease matures, these spots darken and a white fungal growth forms on the undersides. Eventually the entire plant will become infected. Crops can be severely damaged. Unlike other fungal diseases, this plant problem does not overwinter in the soil or on garden trash. Instead the spores are introduced by infected tubers, transplants or seeds. Wind will also carry the disease from nearby gardens. Warm temperatures (70-80˚F) and wet, humid conditions promote its rapid spread.','Plant resistant cultivars when available. Remove volunteers from the garden prior to planting and space plants far enough apart to allow for plenty of air circulation. Water in the early morning hours, or use soaker hoses, to give plants time to dry out during the day — avoid overhead irrigation. Destroy all tomato and potato debris after harvest (see Fall Garden Cleanup).'], 
      'Tomato___Leaf_Mold': ['Tomato-Leaf Mold','Leaf mold is not normally a problem in field-grown tomatoes in northern climates. It can cause losses in tomatoes grown in greenhouses or high tunnels due to the higher humidity found in these environments. Foliage is often the only part of the plant infected and will cause infected leaves to wither and die, indirectly affecting yield. In severe cases, blossoms and fruit can also be infected, directly reducing yield.','Applications should be made prior to infection when environmental conditions favor disease to be the most effective. The first leaf mold infections of the season have been observed in the first week of June in Minnesota high tunnel tomatoes. Fungicide applications should be repeated according to label instructions. It is important to alternate between different chemical families to avoid the development of pathogen resistance to particular active ingredients.'], 
      'Tomato___Septoria_leaf_spot': ['Tomato-Septoria Leaf Spot','Septoria leaf spot is a very common disease of tomatoes. It is caused by a fungus (Septoria lycopersici) and can affect tomatoes and other plants in the Solanaceae family, especially potatoes and eggplant, just about anywhere in the world. Although Septoria leaf spot is not necessarily fatal for your tomato plants, it spreads rapidly and can quickly defoliate and weaken the plants, rendering them unable to bear fruit to maturity. ','Removing infected leaves. Remove infected leaves immediately, and be sure to wash your hands and pruners thoroughly before working with uninfected plants. Consider organic fungicide options: Fungicides containing either copper or potassium bicarbonate will help prevent the spreading of the disease. Begin spraying as soon as the first symptoms appear and follow the label directions for continued management. Consider chemical fungicides: While chemical options are not ideal, they may be the only option for controlling advanced infections. One of the least toxic and most effective is chlorothalonil (sold under the names Fungonil and Daconil).'], 
      'Tomato___Spider_mites Two-spotted_spider_mite': ['Tomato-Spider Mites','Red spider mites mainly feed on plants which are closely related and in the same family as tomato. For example: black nightshades (managu), potatoes, eggplants (biringanya) and weeds like sodom apple. Spider mites get everywhere. You cannot control them on tomato without considering other plants. The mites increase rapidly in numbers during hot and dry conditions. Red spider mite causes more damage and losses in greenhouse tomatoes because of the higher temperatures and drier conditions.','Avoid continuous cropping of tomato and related plants which makes it difficult to control red spider mites, since they always have a plant to feed on. Remove remains (residues) from a previous crop and destroy before planting new crop. Before transferring sticks (stakes) from an infested field to another, wash with soap and water and dry properly under direct sun for a week to avoid transfer of mites. Do the same for twines in the greenhouse. Inspect your crop borders for typical symptoms of red spider mite. Spray water regularly on plants to reduce dust, spider mites do well in dusty conditions. Chemical: When spraying ensure underside of leaf is covered by the chemical. Use fungicides with sulphur, since they reduce populations of mites.'], 
      'Tomato___Target_Spot': ['Tomato-Target Spot','Also known as early blight, target spot of tomato is a fungal disease that attacks a diverse assortment of plants, including papaya, peppers, snap beans, potatoes, cantaloupe, and squash as well as passion flower and certain ornamentals. Target spot on tomato fruit is difficult to control because the spores, which survive on plant refuse in the soil, are carried over from season to season. Read on to learn how to treat target spot on tomatoes.','Remove old plant debris at the end of the growing season; otherwise, the spores will travel from debris to newly planted tomatoes in the following growing season, thus beginning the disease anew. Dispose of the debris properly and don’t place it on your compost pile unless you’re sure your compost gets hot enough to kill the spores. Rotate crops and don’t plant tomatoes in areas where other disease-prone plants have been located in the past year– primarily eggplant, peppers, potatoes or, of course– tomatoes. Rutgers University Extension recommends a three year rotation cycle to reduce soil-borne fungi.'], 
      'Tomato___Tomato_Yellow_Leaf_Curl_Virus': ['Tomato-Yellow Leaf Curl Virus','Tomato yellow leaf curl virus is a DNA virus from the genus Begomovirus and the family Geminiviridae. TYLCV causes the most destructive disease of tomato, and it can be found in tropical and subtropical regions causing severe economic losses.','TYLCV identification based only on symptomatology is unreliable, because similar symptoms can be caused by other viruses or various growing conditions. Use only virus-and whitefly-free tomato and pepper transplants. Transplants should be treated with Capture (bifenthrin) or Venom (dinotefuran) for whitefly adults and Oberon for eggs and nymphs. Imidacloprid or thiamethoxam should be used in transplant houses at least seven days before shipping. Transplants should be produced in areas well away from tomato and pepper production fields.'], 
      'Tomato___Tomato_mosaic_virus': ['Tomato-Mosaic Virus','Mosaic virus overwinters on perennial weeds and is spread by insects that feed on them. Aphids, leafhoppers, whiteflies and cucumber beetles are common garden pests that can transmit this disease. Soil, seed, starter pots and containers can be infected and pass the virus to the plant. Cuttings or divisions from infected plants will also carry the virus.','There are no cures for viral diseases such as mosaic once a plant is infected. As a result, every effort should be made to prevent the disease from entering your garden. Fungicides will NOT treat this viral disease. Plant resistant varieties when available or purchase transplants from a reputable source. Do NOT save seed from infected crops. Spot treat with least-toxic, natural pest control products, such as Safer Soap, Bon-Neem and diatomaceous earth, to reduce the number of disease carrying insects. Harvest-Guard® row cover will help keep insect pests off vulnerable crops/ transplants and should be installed until bloom.'], 
      'Tomato___healthy': ['Healthy Tomato Leaf','It is healthy.','No treatment required.']
      }

model_graph = Graph()
with model_graph.as_default():
    tf_session = tf.compat.v1.Session()
    with tf_session.as_default():
        model = load_model('./models/mobnet.h5')


def index(request):
    context = {'a':False}
    return render(request,'index.html',context)

def predictImage(request):
    
    fileObj = request.FILES['filePath']
    fs = FileSystemStorage()
    filePathName=fs.save(fileObj.name,fileObj)
    filePathName = fs.url(filePathName) 
    if request.user.is_authenticated:
        upload=Uploads.objects.create(user=request.user,img=request.FILES['filePath'],path=filePathName)
        upload.save()
    image_path = '.'+filePathName
    new_img = image.load_img(image_path, target_size=(img_height, img_width))
    img = image.img_to_array(new_img)
    img = np.expand_dims(img, axis=0)
    img = img/255
    with model_graph.as_default():
        with tf_session.as_default():
            prediction = model.predict(img)
    probabilty = prediction.flatten()
    max_prob = probabilty.max()
    index=prediction.argmax(axis=-1)[0]
    class_name = labelInfo[index]
    p = max_prob*100
    if(p<95):
        context = {'filePathName':'./media/assets/error.png','msg':'The inserted image is not a leaf image or multiple leaf images are found','c':True,'a':True} 
    else:
        p = str(p)
        context = {'filePathName':filePathName,'pred':disInfo[class_name][0],'prob':p[0:5],'disDescription':disInfo[class_name][1],'disTreatment':disInfo[class_name][2],'a':True,'c':False}
    return render(request,'index.html',context)

def viewDatabase(request):
    
    import os
    listofImages=os.listdir('./media/')
    listofImagesPath = ['./media/'+i for i in listofImages]
    context = {'listOfImagesPath':listofImagesPath,'listOfImages':listofImages}
    if request.user.is_authenticated:
        if Uploads.objects.filter(user=request.user)!=None:
            uploads = Uploads.objects.filter(user=request.user)
            context['uploads'] = uploads
        else:
            context['uploads'] = Uploads()
    return render(request,'viewDB.html',context) 